replicaCount: 3

ingress:
  enabled: true
  host: nginx.dev.local
image:
  repository: nginx
  tag: "1.29"


resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 1Gi
